<?php

declare(strict_types=1);

namespace WPCBTPro\Tests\Integration\Candidates;

use WPCBTPro\Candidates\CandidateRepository;
use WPCBTPro\Candidates\CandidateService;
use WPCBTPro\Core\Plugin;
use WPCBTPro\Institutions\InstitutionRepository;

/**
 * A candidate's Candidate ID (candidate_ref) is their own registration
 * number whenever one was given and isn't already taken — falling back to
 * the auto-generated CBT-YYYY-NNNNN format only when there's no
 * registration number, or it collides with an existing candidate_ref
 * (candidate_ref has a UNIQUE key; this must never fail the insert).
 */
final class CandidateServiceTest extends \WP_UnitTestCase
{
    public function testRegistrationNumberBecomesTheCandidateId(): void
    {
        $institutionId = (new InstitutionRepository())->ensureDefault();

        /** @var CandidateService $service */
        $service = Plugin::instance()->container()->get(CandidateService::class);
        $id = $service->create([
            'institution_id' => $institutionId,
            'first_name' => 'Ada',
            'last_name' => 'Lovelace',
            'registration_number' => '2024/CS/REF-001',
        ]);

        $candidate = (new CandidateRepository())->find($id);
        self::assertSame('2024/CS/REF-001', $candidate['candidate_ref']);
    }

    public function testNoRegistrationNumberFallsBackToTheAutoGeneratedFormat(): void
    {
        $institutionId = (new InstitutionRepository())->ensureDefault();

        /** @var CandidateService $service */
        $service = Plugin::instance()->container()->get(CandidateService::class);
        $id = $service->create([
            'institution_id' => $institutionId,
            'first_name' => 'Grace',
            'last_name' => 'Hopper',
        ]);

        $candidate = (new CandidateRepository())->find($id);
        self::assertMatchesRegularExpression('/^CBT-\d{4}-\d{5}$/', $candidate['candidate_ref']);
    }

    public function testACollidingRegistrationNumberFallsBackInsteadOfFailing(): void
    {
        $institutionId = (new InstitutionRepository())->ensureDefault();

        /** @var CandidateService $service */
        $service = Plugin::instance()->container()->get(CandidateService::class);

        $firstId = $service->create([
            'institution_id' => $institutionId,
            'first_name' => 'Marie',
            'last_name' => 'Curie',
            'registration_number' => 'DUPLICATE-REF',
        ]);

        // A second candidate whose registration number happens to already be
        // in use as someone else's candidate_ref must still be creatable.
        $secondId = $service->create([
            'institution_id' => $institutionId,
            'first_name' => 'Rosalind',
            'last_name' => 'Franklin',
            'registration_number' => 'DUPLICATE-REF',
        ]);

        $repository = new CandidateRepository();
        $first = $repository->find($firstId);
        $second = $repository->find($secondId);

        self::assertSame('DUPLICATE-REF', $first['candidate_ref']);
        self::assertNotSame('DUPLICATE-REF', $second['candidate_ref']);
        self::assertMatchesRegularExpression('/^CBT-\d{4}-\d{5}$/', $second['candidate_ref']);
    }
}
